site :opscode

cookbook "apt"
cookbook "build-essential"
cookbook "chef_handler"
cookbook "dmg"
cookbook "git"
cookbook "mongodb"
cookbook "mysql"
cookbook "nodejs"
cookbook "openssl"
cookbook "php"
cookbook "python"
cookbook "redisio"
cookbook "runit"
cookbook "ulimit"
cookbook "windows"
cookbook "xml"
cookbook "yum"

